/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as LayoutImport } from './routes/_layout'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as DashboardItemsImport } from './routes/dashboard/items'
import { Route as DashboardAdminImport } from './routes/dashboard/admin'
import { Route as LayoutSignupImport } from './routes/_layout/signup'
import { Route as LayoutResetPasswordImport } from './routes/_layout/reset-password'
import { Route as LayoutRecoverPasswordImport } from './routes/_layout/recover-password'
import { Route as LayoutLoginImport } from './routes/_layout/login'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardItemsRoute = DashboardItemsImport.update({
  path: '/items',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAdminRoute = DashboardAdminImport.update({
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

const LayoutSignupRoute = LayoutSignupImport.update({
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResetPasswordRoute = LayoutResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRecoverPasswordRoute = LayoutRecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginRoute = LayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/recover-password': {
      preLoaderRoute: typeof LayoutRecoverPasswordImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reset-password': {
      preLoaderRoute: typeof LayoutResetPasswordImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup': {
      preLoaderRoute: typeof LayoutSignupImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/admin': {
      preLoaderRoute: typeof DashboardAdminImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/items': {
      preLoaderRoute: typeof DashboardItemsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/settings': {
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/': {
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutLoginRoute,
    LayoutRecoverPasswordRoute,
    LayoutResetPasswordRoute,
    LayoutSignupRoute,
    LayoutIndexRoute,
  ]),
  DashboardRoute.addChildren([
    DashboardAdminRoute,
    DashboardItemsRoute,
    DashboardSettingsRoute,
    DashboardIndexRoute,
  ]),
])

/* prettier-ignore-end */
